name: Continuous Integration
on: 
  - push
jobs:
  style:
    name: style
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check lua/
          version: latest
